/**
 * This code was generated by Builder.io.
 */
"use client";
import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
  DialogTrigger,
  DialogOverlay,
  DialogClose,
} from "@/components/ui/dialog";

type HeaderProps = {
  logo: string;
  activeMenuItem: string;
};

const Header: React.FC<HeaderProps> = ({ logo, activeMenuItem }) => {
  const navItems = [
    { text: "Home", isSemibold: activeMenuItem === "home", href: "/" },
    {
      text: "About Us",
      isSemibold: activeMenuItem === "about",
      href: "/about",
    },
    {
      text: "Results",
      isSemibold: activeMenuItem === "results",
      href: "/results",
    },
    {
      text: "Achiever's Message",
      isSemibold: activeMenuItem === "achievers",
      href: "/achievers",
    },
    {
      text: "New Batch",
      isSemibold: activeMenuItem === "new-batch",
      isHighlighted: true,
      href: "/new-batch",
    },
    {
      text: "Contact Us",
      isSemibold: activeMenuItem === "contact",
      href: "/contact",
    },
    {
      text: "FB Updates",
      target: "_blank",
      href: "https://www.facebook.com/cat2iimbymm",
    },
  ];

  const isExternalLink = (url) => {
    if (url.includes("http://") || url.includes("https://")) {
      return true;
    }
    return false;
  };

  return (
    <header className="flex gap-10 items-center self-start text-sm font-light tracking-tight text-center text-black w-full">
      <a href="/">
        <img
          loading="lazy"
          src={logo}
          alt="Company Logo"
          className="object-contain shrink-0 self-stretch max-w-full aspect-[1.26] w-[152px]"
        />
      </a>
      <nav className="max-md:hidden">
        {navItems.map((item, index) => (
          <a
            key={index}
            href={item.href}
            target={isExternalLink(item.href) ? "_blank" : "_self"}
            className={`self-stretch my-auto ml-10 ${
              item.isSemibold ? "font-semibold  border-b-2 border-black" : ""
            } ${item.isHighlighted ? "text-indigo-700" : ""} ${
              item.text.includes(" ") ? "basis-auto" : ""
            }`}
          >
            {item.text}
          </a>
        ))}
      </nav>
      <nav className="ml-auto mr-4">
        <Dialog>
          <DialogTrigger>
            <img
              width="32"
              className="cursor-pointer ml-auto hidden max-md:block"
              src="/hamburger.svg"
              alt="Menu"
            ></img>
          </DialogTrigger>
          <DialogOverlay />
          <DialogContent className="p-4 w-full bg-white h-full shadow-lg">
            <DialogDescription className="h-full mt-10">
              <div className="flex flex-col h-full mt-4">
                {navItems.map((item, index) => (
                  <a
                    key={index}
                    href={item.href}
                    className={`mt-4 text-xl ml-10 ${
                      item.isSemibold ? "font-semibold" : ""
                    } ${item.isHighlighted ? "text-indigo-700" : ""} ${
                      item.text.includes(" ") ? "basis-auto" : ""
                    }`}
                  >
                    {item.text}
                  </a>
                ))}
              </div>
            </DialogDescription>
          </DialogContent>
        </Dialog>
      </nav>
    </header>
  );
};

export default Header;
