/**
 * This code was generated by Builder.io.
 */
import React from "react";

type HeaderProps = {
  logo: string;
};

const Header: React.FC<HeaderProps> = ({ logo }) => {
  const navItems = [
    { text: "Home", isSemibold: true },
    { text: "About Us", isSemibold: false },
    { text: "Results", isSemibold: false },
    { text: "Achiever's Message", isSemibold: false },
    { text: "Super 60 New Batch", isSemibold: true, isHighlighted: true },
  ];

  return (
    <header className="flex gap-10 items-center self-start text-sm font-light tracking-tight text-center text-black">
      <img
        loading="lazy"
        src={logo}
        alt="Company Logo"
        className="object-contain shrink-0 self-stretch max-w-full aspect-[1.26] w-[152px]"
      />
      <nav>
        {navItems.map((item, index) => (
          <a
            key={index}
            href="#"
            className={`self-stretch my-auto ml-10 ${
              item.isSemibold ? "font-semibold" : ""
            } ${item.isHighlighted ? "text-indigo-700" : ""} ${
              item.text.includes(" ") ? "basis-auto" : ""
            }`}
          >
            {item.text}
          </a>
        ))}
      </nav>
    </header>
  );
};

export default Header;
