/**
 * This code was generated by Builder.io.
 */
import React from "react";

type HeaderProps = {
  logo: string;
  activeMenuItem: string;
};

const Header: React.FC<HeaderProps> = ({ logo, activeMenuItem }) => {
  const navItems = [
    { text: "Home", isSemibold: activeMenuItem === "home", href: "/" },
    {
      text: "About Us",
      isSemibold: activeMenuItem === "about",
      href: "/about",
    },
    {
      text: "Results",
      isSemibold: activeMenuItem === "results",
      href: "/results",
    },
    {
      text: "Achiever's Message",
      isSemibold: activeMenuItem === "achievers",
      href: "#",
    },
    {
      text: "Super 60 New Batch",
      isSemibold: activeMenuItem === "new-batch",
      isHighlighted: true,
      href: "/new-batch",
    },
    {
      text: "Contact Us",
      isSemibold: activeMenuItem === "contact",
      href: "/contact",
    },
  ];

  return (
    <header className="flex gap-10 items-center self-start text-sm font-light tracking-tight text-center text-black">
      <img
        loading="lazy"
        src={logo}
        alt="Company Logo"
        className="object-contain shrink-0 self-stretch max-w-full aspect-[1.26] w-[152px]"
      />
      <nav>
        {navItems.map((item, index) => (
          <a
            key={index}
            href={item.href}
            className={`self-stretch my-auto ml-10 ${
              item.isSemibold ? "font-semibold  border-b-2 border-black" : ""
            } ${item.isHighlighted ? "text-indigo-700" : ""} ${
              item.text.includes(" ") ? "basis-auto" : ""
            }`}
          >
            {item.text}
          </a>
        ))}
      </nav>
    </header>
  );
};

export default Header;
