/**
 * This code was generated by Builder.io.
 */
"use client";
import React, { useMemo } from "react";
import Testimonial from "./Testimonial";
import Footer from "./Footer";
import AchieversVideos from "./AchieversVideos/AchieversVideos";

export const allTestimonials = [
  {
    name: "Unnati Mangal",
    result: "IIM Shillong 23-25",
    text: `Thank you so much sir for always being a mentor. The journey
                with you and CAT2IIM has played a great role in my CAT 2022
                preparation. I could score 97.82%tile and join IIM Shillong just
                because of your constant guidance, motivation and short tricks.
                I want to express my sincere appreciation to CAT2IIM and Manoj
                Sir for the one-to-one mentoring sessions provided during my CAT
                preparation. The personalised guidance and short tricks shared
                were incredibly effective in enhancing my problem-solving
                skills. The phase-wise strategy and structured plan for mocks
                were particularly beneficial, giving me a clear roadmap to
                follow and helping me track my progress effectively. This
                approach not only improved my confidence but also ensured I was
                well-prepared for each phase of the preparation. Thank you for
                your unwavering support and for equipping me with the tools I
                need to succeed in the CAT 2022 & SNAP 2022 (97.84%tile) exam.`,
    photoURL: "/unnati-mangal.jpeg",
  },
  {
    name: "Shubham Goel",
    result: "XLRI Delhi 24-26",
    text: `I am thrilled to share my journey from CAT preparation to
                securing a coveted seat at XLRI. 🌟 𝐆𝐫𝐚𝐭𝐢𝐭𝐮𝐝𝐞 𝐭𝐨 𝐂𝐀𝐓𝟐𝐈𝐈𝐌 🙏
                First and foremost, I want to express my heartfelt gratitude to
                CAT2IIM, the coaching institute that played a pivotal role in my
                success. Their unwavering commitment to excellence, personalised
                guidance, and innovative pedagogy truly set them apart. 🚀 𝐓𝐡𝐞
                𝐂𝐀𝐓𝟐𝐈𝐈𝐌 𝐏𝐞𝐝𝐚𝐠𝐨𝐠𝐲 📚 CAT2IIM's approach is unique and effective.
                Here's what stood out for me: 
                
                1. 𝐈𝐧𝐝𝐢𝐯𝐢𝐝𝐮𝐚𝐥𝐢𝐳𝐞𝐝 𝐏𝐫𝐞𝐩𝐚𝐫𝐚𝐭𝐢𝐨𝐧:
                CAT2IIM recognizes that every student is different. They tailor
                their coaching to meet individual needs, ensuring a personalised
                learning experience. 
                
                2. 𝐄𝐱𝐚𝐦 𝐒𝐭𝐫𝐚𝐭𝐞𝐠𝐲: Their expert faculty
                provided invaluable insights into tackling CAT, SNAP, NMAT, and
                XAT. Their mock test strategies were spot-on, which helped boost
                my percentile. 
                3. 𝐏𝐈 𝐏𝐫𝐞𝐩𝐚𝐫𝐚𝐭𝐢𝐨𝐧: CAT2IIM's interview
                preparation sessions were game-changers. They helped me build
                confidence, articulate my thoughts, and present my best self
                during interviews. 𝐌𝐲 𝐒𝐭𝐞𝐥𝐥𝐚𝐫 𝐏𝐞𝐫𝐟𝐨𝐫𝐦𝐚𝐧𝐜𝐞 🌟 - CAT: 98.47 -
                SNAP: 97.5 - NMAT: 237 - XAT: 95.3 𝐂𝐚𝐥𝐥𝐬 𝐚𝐧𝐝 𝐂𝐨𝐧𝐯𝐞𝐫𝐬𝐢𝐨𝐧𝐬 📞 I
                received interview calls from some of the top B-schools: - XLRI
                - IIFT - MDI - NMIMS - IIM Rohtak And the good news doesn't end
                there! I converted NMIMS BA, MDI HRM and I’m also waitlisted for
                IIFT’s Flagship program. 🎓 𝐉𝐨𝐢𝐧 𝐭𝐡𝐞 𝐂𝐀𝐓𝟐𝐈𝐈𝐌 𝐅𝐚𝐦𝐢𝐥𝐲!🤝 CAT2IIM's
                success stories are built on word-of-mouth recommendations.
                Let's spread the word and help more aspirants achieve their
                dreams. 🌈 Thank you, CAT2IIM, for being my guiding light! 🙌`,
    photoURL: "/shubham-goel.jpeg",
  },
  {
    name: "Sourav Ranjan",
    result: "NMIMS Mumbai 23 - 25",
    text: `For someone like me who quit maths after class 10 and didn't even remember the basics. Your motivation to slowly work on basics and then on advance really helped. 

The USP of your classes is that you sit with each student, identify there deficiency and give a customised preparation strategy. The best investment if you want to crack CAT/NMAT/XAT. 

If you're not good in Quant and LR, you will need a preparation and exam strategy. Join him, it's a no brainer.

Having spent a year at NMIMS Mumbai, I must say that persistence is the name of the game if you want to succeed. 
I had days when I almost gave up but Manoj Sir pushed to keep moving forward. Thank you Manoj Sir.`,
    photoURL: "/sourav-ranjan.jpeg",
  },
  {
    name: "Dr. Purnopama",
    result: "IIM Udaipur 23-25",
    text: `Thankyou so much sir for being such a great mentor for us. You have been a constant source of motivation whenever our motivation levels went downhill. CAT2IIM grooms you not just to face the exam, but also guides you in each and every step of the exam. The level of personal attention and guidance you give to any student is really difficult to find anywhere else. Hat's off to your hardwork!

After joining IIM Udaipur my life had been very different, the transition from being a Doctor to a MBA student is very enriching and exciting.`,
    photoURL: "/dr-purnopama.jpeg",
  },
  {
    name: "Shubham Dwivedi",
    result: "ISB 25-26",
    text: `Joining Manoj Sir's online classes at CAT2IIM was a turning point in my journey to crack CAT, XAT, and GMAT. Attending his sessions from the comfort of my home, I found myself learning in a way that was both engaging and incredibly effective. Manoj Sir has a unique way of breaking down complex concepts, making even the toughest topics seem manageable.

But what truly sets him apart is his genuine care for his students' success. He didn't just focus on the academics; he was deeply involved in every aspect of my preparation. From nailing down my test strategies to perfecting my essays and honing my interview skills, Manoj Sir was there every step of the way.

When I started receiving interview calls from ISB, SPJIMR, BITSOM, IMT Ghaziabad, and several IIMs, including the new and baby IIMs, it felt like a dream come true. But I knew it wasn’t just luck—it was the result of consistent guidance and support. Manoj Sir’s approach to mentorship was personal and impactful. He knew exactly how to push me when I needed it and how to support me when I doubted myself.

Looking back, I can't imagine going through this journey without Manoj Sir and CAT2iim. His classes  were more than just lessons—they were the foundation of my success. If you’re serious about your MBA dreams, CAT2IIM is where you need to be.`,
    photoURL: "/shubham-dwivedi.jpeg",
  },
  {
    name: "Chirag Kaushik",
    result: "IIM Ranchi 24-26",
    text: `CAT2IIM has been instrumental in my CAT preparation journey. The structured approach, comprehensive study material, and tailored guidance provided a clear path to success. Mahajan Sir, in particular, played a significant role in my preparation. His insights and guidance not only strengthened my understanding of key concepts but also boosted my confidence for the interview process. Thanks to CAT 2 IIM and Mahajan Sir, I felt well-prepared and confident on exam day, ultimately helping me secure admission to IIM Ranchi. I highly recommend CAT2IIM to anyone serious about their CAT prep.`,
    photoURL: "chirag-kaushik.jpeg",
  },
  {
    name: "Sanjay Jaiswal",
    result: "IIM Indore  23-25",
    text: `
      I owe my success in converting IIM Indore & other Top B-schools to CAT2IIM and the guidance of Manoj Mahajan Sir. His teaching style is engaging and  his tips & tricks made learning much easier. He also personally mentored me, helping me become an achiever.
    `,
    photoURL: "./sanjay-jaiswal.jpeg",
  },
  {
    name: "Insha",
    result: "Converted SIBM B",
    text: `
      I would like to thank CAT2IIM for mentoring me throughout the CAT journey as the experience was nothing short of transformative. From the outset, CAT2IIM teaches amazing tricks and shortcuts significantly improving my problem-solving skills and efficiency.

The one-on-one mentoring sessions were particularly valuable. The personalized approach to exam and interview preparation, including detailed mock interviews, was instrumental in honing my skills and boosting my confidence. The guidance provided was immaculate—strategically tailored to address my strengths and weaknesses, ensuring that I was well-prepared for every challenge.

Thanks to CAT2IIM unwavering support and expert advice, I successfully got my offer from SIBM Bangalore. Their thorough guidance throughout the journey made a significant difference, and I genuinely felt supported at every step. I highly recommend CAT2IIM to anyone serious about excelling in their CAT & OMETs  journey and achieving their goals.
    `,
    photoURL: "./insha.jpeg",
  },
  {
    name: "Anjali Kapoor",
    result: "IIM Lucknow (IPMX) 23 -24",
    text: `Manoj sir was a great help in quant preparation. He made complex concepts easy to understand and was always patient and supportive. Thanks to his guidance, I was able to improve my Quant skills significantly and get through IIM Lucknow`,
    photoURL: "./anjali-kapoor.jpeg",
  },
  {
    name: "Saad",
    result: "Converted DSE",
    text: `When I first joined CAT2IIM by Manoj Mahajan, I was a CAT candidate in a poor situation as I scored only 43 percentile in CAT 2022. Although I had personalized strategies regarding the preparation of the exam, Manoj Sir changed my strategy completely for the better. I believe that his tricks/shortcuts and the DPACTS(LRDI Strategy) mantra were instrumental in helping me score an impressive mark of 94.64 percentile in CAT 23. Actually, it was all possible because CAT2IIM offered me the attention I needed and taught me the most effective strategies. In my case, I would say Manoj Sir's coaching should not be missed if the candidate is serious about cracking CAT and getting the right management education.
Because of Manoj Sir's guidance, I was able to get calls from colleges like IIT Roorkee, DBE, DSE, DFS & JMI and converted MBA at Delhi School of Economics (DSE) & Jamia Millia Islamia (JMI). This success in securing admissions to prestigious institutions is a testament to the effectiveness of CAT2IIM's preparation program and Manoj Sir's mentorship.`,
    photoURL: "./saad.jpeg",
  },
  {
    name: "Harshit",
    result: "GIM 23-25",
    text: "",
    photoURL: "./harshit.jpeg",
  },
  {
    name: "Kanushka",
    result: "Great Lakes Gurgaon ( PGPM ) 24 -25",
    text: "",
    photoURL: "./kanushka.jpeg",
  },
  {
    name: "Karen",
    result: "IIFT call 2022",
    text: "",
    photoURL: "./karen.jpeg",
  },
  {
    name: "Sahil",
    result: "SIBM Pune & SCMHRD Call 2022",
    text: "",
    photoURL: "./sahil.jpeg",
  },
  {
    name: "Sushma",
    result: "NMIMS Mumbai call 2023",
    text: "",
    photoURL: "./sushma.jpeg",
  },
  {
    name: "Aditya",
    result: "IIM CAP Call 2023",
    text: "",
    photoURL: "./aditya.jpeg",
  },
  {
    name: "Bharat",
    result: "IIM Bodh Gaya Call 2023",
    text: "",
    photoURL: "./bharat.jpeg",
  },
  {
    name: "Avi",
    result: "IIM CAP Call 2022",
    text: "",
    photoURL: "./avi.jpeg",
  },
];

export default function MentorFooter() {
  const testimonials = useMemo(() => {
    return allTestimonials.slice(0, 2);
  }, [allTestimonials]);
  return (
    <div className="flex flex-col items-center rounded-none mt-16 max-md:mt-10">
      {/* <iframe
        src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fcat2iimbymm&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=true&appId"
        width="340"
        height="500"
        style={{ border: "none", overflow: "hidden" }}
        scrolling="no"
        frameBorder="0"
        allowFullScreen
        allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"
      ></iframe> */}
      <div className="z-10 -mt-1.5 text-2xl font-semibold text-center text-black">
        Meet the Mentor
      </div>
      <img
        loading="lazy"
        src="./manoj.webp"
        className="object-contain mt-10 max-w-full aspect-square w-[210px]"
      />
      <div className="mt-6 text-2xl font-semibold leading-none text-center text-black">
        Manoj Mahajan
      </div>
      <div className="text-base font-semibold leading-8 text-center text-zinc-800">
        “Not Just An Educator, But A Mentor”
      </div>
      <div className="mt-10 px-4 text-xl font-semibold leading-8 max-md:leading-[1.5] text-center text-indigo-700 w-[613px] max-md:max-w-full">
        Quant & LRDI Trainer with over 20 years of teaching experience with
        Career Launcher, TIME, Tathagat and Unacademy. Manoj sir has been
        teaching at CAT2IIM for more than 2 years now producing excellent
        results for his students.
      </div>
      <div className="self-end mt-20 w-full max-w-[1376px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col justify-center">
          <AchieversVideos numVideos={3} />
        </div>
        <a
          href="/achievers"
          className="mt-8 flex justify-end items-center cursor-pointer pr-2"
        >
          View all messages
          <img
            className="ml-2"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/376b86ae6715805320f789525e320d8d6afd521a9f6f25557c2323cf2ee8fab9?placeholderIfAbsent=true&apiKey=9bca9c6557e04269a5028755255fb6a9"
          />
        </a>
        <div className="flex gap-5 max-md:flex-col justify-center mt-20 max-md:mt-10">
          {testimonials.map((testimonial) => (
            <Testimonial key={testimonial.name} {...testimonial} />
          ))}
        </div>
        <a
          href="/results"
          className="mt-8 flex justify-end items-center cursor-pointer pr-2"
        >
          View all testimonials
          <img
            className="ml-2"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/376b86ae6715805320f789525e320d8d6afd521a9f6f25557c2323cf2ee8fab9?placeholderIfAbsent=true&apiKey=9bca9c6557e04269a5028755255fb6a9"
          />
        </a>
      </div>
      <Footer />
    </div>
  );
}
