/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { RxExternalLink } from "react-icons/rx";

type StatCardProps = {
  icon: string;
  stats: { value: string; label: string }[];
};

const StatCard: React.FC<StatCardProps> = ({ icon, stats }) => {
  return (
    <a
      target="_blank"
      href="https://www.youtube.com/@CAT2IIMByManojMahajan"
      className="flex flex-col self-start mt-6 items-center flex-1 max-md:m-auto"
    >
      <div className="flex flex-col relative justify-center items-center px-9 bg-red-600 h-[172px] w-[172px] max-md:px-5">
        <RxExternalLink className="absolute top-2 right-2 text-white" />
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain aspect-[1.43] w-[86px]"
        />
      </div>
      <div className="flex gap-5 justify-between items-start mt-11 text-center max-md:mt-10">
        {stats.map((stat, index) => (
          <React.Fragment key={index}>
            {index > 0 && (
              <div className="shrink-0 self-stretch w-px h-20 border border-indigo-700 border-solid" />
            )}
            <div className="flex flex-col">
              <div className="text-2xl font-bold text-indigo-700">
                {stat.value}
              </div>
              <div className="mt-5 text-xs tracking-wide text-black">
                {stat.label}
              </div>
            </div>
          </React.Fragment>
        ))}
      </div>
    </a>
  );
};

export default StatCard;
