/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeroImageProps {}

const HeroImage: React.FC<HeroImageProps> = () => {
  return (
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src="./female-success.webp"
        alt="CAT Cracking illustration"
        className="object-contain grow w-full rounded-lg aspect-[1.95] max-md:mt-10 max-md:max-w-full"
      />
    </div>
  );
};

export default HeroImage;
